// Core agent operations
export {
  listAgents,
  createAgent,
  selfRegisterAgent,
  discoverAgents,
  updateAgent,
  heartbeatAgent,
  listRecommendedTasks,
  listAgentAssignments,
  getAgentInbox,
  claimAgentTask,
  updateAgentAssignment,
  getAgentCapabilityGapAnalysis,
  getAgentRunResourceTrend,
  healthCheck,
  markOfflineAgents,
  getAgentCollaborators,
} from './core.js';

// Messaging operations
export {
  listAuditLogs,
  listSecurityEvents,
  exportSecurityEvents,
  securityEventsDailyTrend,
  securityEventsByAgent,
  sendAgentMessage,
  getAgentMessages,
} from './messaging.js';

// Reputation and experience operations
export {
  getAgentReputation,
  listReputations,
  recalculateReputation,
  getAgentReputationHistory,
  listAgentExperiences,
  createAgentExperience,
  getAgentExperience,
  updateAgentExperience,
  deleteAgentExperience,
  recommendExperiences,
  getExperiencesStats,
} from './reputation.js';

// Productivity and analytics operations
export {
  getAgentProductivity,
  getAgentRunResourceUsage,
  getAgentProductivityTrend,
  getAgentProductivityAlerts,
  getAgentProductivityByKind,
  getAgentProductivityHourlyHeatmap,
  getAgentProductivityCalendarHeatmap,
  getAgentProductivityWeeklyComparison,
  getAgentFailureReasons,
  getAgentFailureErrorPatterns,
  getAgentHealth,
  getAgentHealthTrend,
  getAgentHealthStateTransitions,
  getAgentHealthAlerts,
  getExperiencesLowConfidence,
  getExperiencesScatter,
  getExperiencesReuseTrend,
  getExperiencesConfidenceDecayForecast,
  getExperiencesDecayByDomain,
  getExperiencesDecayByTaskType,
  getExperiencesConfidenceDistribution,
  getExperiencesSourceDistribution,
  getExperiencesPropagationChain,
  getExperiencesSkillCoverageRadar,
  shareAgentExperience,
  learnFromExperience,
  listSharedExperiences,
  autoExtractExperiences,
  authorizeCrossProjectAgent,
  revokeCrossProjectAgent,
  listAgentCrossProjects,
  listProjectExternalAgents,
  discoverCrossProjectAgents,
  findCapableAgentsCrossProject,
  applyExperienceDecay,
  validateExperience,
  getExperienceValidationStats,
  decayAllExperiences,
  suggestCapabilityAdaptation,
  applyCapabilityAdaptation,
  bindAgentSandbox,
  getAgentSandbox,
  getSandboxViolationsByAgent,
  getConflictsByAgent,
  getAgentSkillMatching,
  getAgentTaskHandoffStats,
  getAgentWorkloadForecast,
  getAgentSpecializationEvolution,
  getAgentExperiencesDecayAlerts,
  getAgentCrossProjectEfficiency,
  getAgentCapabilitySupplyDemand,
  getAgentIdleRanking,
} from './productivity.js';